### ISSUE TITLE
The display of GUAVA window is blank as shown , so I could not analyze further.Does anyone know how to solve it?

### ISSUE THREAD

**Issue by yabin2018** [MayurDivate/GUAVA#16]
![github](https://user-images.githubusercontent.com/44997654/48406989-c870f700-e770-11e8-988d-9c8ac15e7365.png)

**Comment by MayurDivate** [comment]
Hi,

I have just tried guava on the new machine.
It works perfectly for me. 
There are no issues regarding UI, I suggest you to update Java.

Cheers,
Mayur

**Comment by yabin2018** [comment]
Thanks for your reply. My Java version is 1.8.0. Is this a version issue?

**Comment by MayurDivate** [comment]
GUAVA works well with Java 1.8 or higher version.

But could you please give a try with the updated Java version.
Because this issue is something more about Java than GUAVA. 

Thanks,
Mayur
