### ISSUE TITLE
Problem with Bowtie Dependence

### ISSUE THREAD

**Issue by LeonardoLed** [MayurDivate/GUAVA#17]
Hi there, I have tried to run de GUAVA.jar, the option number one: ATAC-SEQ DATA ANALYSIS, but the program shows that I need botwie 1.
I have already installed bowtie 1 in my PC.  Do you know what is the problem?
![error](https://user-images.githubusercontent.com/33387734/48884746-6ad15000-edeb-11e8-8e3b-5f9fe9c59577.JPG)
![bowtie](https://user-images.githubusercontent.com/33387734/48884753-6f960400-edeb-11e8-85a7-866e47aa59c5.JPG)

**Comment by LeonardoLed** [comment]
the problem has solved, thank you

**Comment by jclv123** [comment]
Hi @LeonardoLed, how did you manage to solve this issue? I am running into the same one? 

Thanks
