### ISSUE TITLE
GUAVA missing dependancies error

### ISSUE THREAD

**Issue by Saelm1987** [MayurDivate/GUAVA#19]
Hi
I am having issues with GUAVA
Every thing looks fine. However, when I run ATAC analysis the I get this error MACS2 is missing. I am sure that I do have macs2 on my system but it the most updated one. Does GUAVA prefer a specific version of macs2? if yes how I could downgrade my macs2 version so that it will be compatible with GUAVA?

>>> >> > Installing dependencies > >> >>>
#++++++++++++++++++++++++++++++++++++++++++++++++++++++++++#
>>>>> FOUND: java <<<<<
>>>>> FOUND: bedtools <<<<<
>>>>> FOUND: bowtie <<<<<
>>>>> FOUND: bowtie2 <<<<<
>>>>> FOUND: cutadapt <<<<<
>>>>> FOUND: fastqc <<<<<
>>>>> FOUND: samtools <<<<<
>>>>> FOUND: picard <<<<<
>>>>> FOUND: igv <<<<<
>>>>> FOUND: bedGraphToBigWig <<<<<

>>> MACS2 is already installed ! 
>>>>>>>>> Finished <<<<<<<<<

When I try to run ATAC-seq Data Analysis I get this error:

GUAVA version 1
Operating System of machine :Linux
		cutadapt:		Working!
		bowtie:		Working!
		bowtie2:	Working!
		fastqc:		Working!
		samtools:	Working!
		MACS2 version (macs2 2.1.1.20160309) :			NOT FOUND !!!
		Picard:		Working!
		bedtools:		Working!
		bedGraphToBigWig:		Working!
		igv:		Working!

There are missing dependancies!
Please use configure.sh to install dependencies.
If you are having difficulties in installing dependencies, please report issue at *GitHub*.
>>> https://github.com/MayurDivate/GUAVASourceCode/issues
EXIT(GUAVA) ... 

Please let me know how to fix this error.

Thank you

**Comment by MayurDivate** [comment]
Hi, this should help you 
[MACS2 error](https://github.com/MayurDivate/GUAVASourceCode/issues/3#issuecomment-438342315)
