### ISSUE TITLE
adding a new geome to the library so is in pull-down menu

### ISSUE THREAD

**Issue by jrainger3** [MayurDivate/GUAVA#20]
How do I add a genome (eg. gagGal6) so it is visible in the pull-down menu of the GUI in "ATAC-seq Data Analysis" mode?
I have installed galgal6.genome in /GUAVA-1/lib/genomes and also successfully run 
$ sh ./configure.sh

Thanks.
Joe

**Comment by MayurDivate** [comment]
Hi Joe,

I am afraid that you cannot do it straight forward. 
I will have to make same changes in the source code to add it to the GUAVA.

Thanks,
Mayur

**Comment by Dingersrun** [comment]
Can I install it on a Window computer?

**Comment by tcolston** [comment]
Has a workaround been provided for using custom genome assemblies?

**Comment by MayurDivate** [comment]
> Can I install it on a Window computer?

No, you need either linux or Mac OS.

**Comment by MayurDivate** [comment]
> Has a workaround been provided for using custom genome assemblies?

I am afraid that there is no way to use custom genome assemblies.
