### ISSUE TITLE
macs2 update

### ISSUE THREAD

**Issue by sarahmklee** [MayurDivate/GUAVA#21]
Hello, 

I installed GUAVA and I tried to open it as I have all the dependencies already downloaded. However, GUAVA is unable to open as the macs2 version does not match. 

This was the error:
 macs2 version (macs2 2.1.1.20160309) :                  NOT FOUND !!!

macs2 I have right now is version 2.1.2 

Is there a way to fix this issue?

Thanks.

**Comment by MayurDivate** [comment]
Hi, this should help you 
[MACS2 error](https://github.com/MayurDivate/GUAVASourceCode/issues/3#issuecomment-438342315)
