### ISSUE TITLE
Error at the end of DESeq2

### ISSUE THREAD

**Issue by padmina** [MayurDivate/GUAVA#22]
Hi,

We got this error code at the end of DESeq2. 

Error in grid.Call(C_textBounds, as.graphicsAnnot(x$label), x$x, x$y,  : 
 X11 font -adobe-helvetica-%s-%s-*-*-%d-*-*-*-*-*-*-*, face 1 at size 9 could not be loaded
Calls: print ... <Anonymous> -> widthDetails -> widthDetails.text -> grid.Call
Execution halted

Please let us know how to fix it.

Thank you.

**Comment by MayurDivate** [comment]
Hi,

Could you possibly share your system details?
Also, give a try again.

Mayur

**Comment by padmina** [comment]
Hi!

Thanks for the reply. We retried it with 

library(Cairo)
options(bitmapType="cairo")

and it worked!

Thanks again.

Padmina
