### ISSUE TITLE
Problem with installing miniconda

### ISSUE THREAD

**Issue by re2srm** [MayurDivate/GUAVA#24]
Hello, 

When i run the configuration, it installs all the r packages and then miniconda until this message pops up. However, when I close the terminal and run it again I keep getting the same message. 

which conda shows the correct path where minicoda is being installed.

** >>>>>>>>>>> unable to load conda <<<<<<<<<<<<<<< **
** >>>>>>>> please CLOSE THE TERMINAL <<<<<<<<<<<<< **
** ++++++++ Then open the new terminal ++++++++++++ **
** +++++++ again run the configure.sh +++++++++++ **

**Comment by MayurDivate** [comment]
Hi, 

Did you complete the "conda" installation? 
If yes then simply run the following command and let me know the output.
```which conda```

Following video could be helpful for you,
[video](https://youtu.be/C-9URYWSquI)

Best wishes!
Mayur
