### ISSUE TITLE
MACS2 Dependency

### ISSUE THREAD

**Issue by lailamargaret** [MayurDivate/GUAVA#25]
hi! cool tool, i'm really interested in using it. I already had MACS2 installed but used your bash script for installing dependencies anyway. When I run the .jar, everything is working except MACS2 which it reports is not found. Any idea why it can't find my version of MACS2? Thanks!

**Comment by MayurDivate** [comment]
If you are not able to install macs2, this should help you!
[MACS2 error](https://github.com/MayurDivate/GUAVASourceCode/issues/3#issuecomment-438342315)
