### ISSUE TITLE
Error when executing java –jar GUAVA.jar

### ISSUE THREAD

**Issue by ge2sasag** [MayurDivate/GUAVA#26]
Hi,

Thank you for this useful software! I installed all the requirements (linux mint Cinnamon Tina) but I get this error when executing the jar file:

java –jar GUAVA.jar
Error: could not find or load main class –jar
Caused by: java.lang.ClassNotFoundException: –jar

How could I solve this?

Thank you in advance!
Gema

**Comment by MayurDivate** [comment]
Dear @ge2sasag,

I just noticed that you are using a wrong character in the command i.e. "–".
You should use this one "-".
Actually both looks very very similar but one is slightly short in length. 
It should work for you If you use following command.
```
java -jar GUAVA.jar
```

Best regards,
Mayur
