### ISSUE TITLE
Unmatched versions of MACS2 in bash script, and jar GUI

### ISSUE THREAD

**Issue by Liberatark** [MayurDivate/GUAVA#27]
Hi Man, It is a really cool tool. I found the problem is: when I used bash script to intall dependencies, it install MACS2 2.1.2; but when I run jar, It required MACS2 2.1.1.
Is there any efficient way to solve the problem? Many thanks.

**Comment by MayurDivate** [comment]
Hi Liberatark, 
This issue has been already addressed here  [link](https://github.com/MayurDivate/GUAVASourceCode/issues/3#issuecomment-438342315).

Thanks,
Mayur

**Comment by Liberatark** [comment]
Thanks Man, solved the problem. Excited to use it.
